pipeline:
  deploy:
    image: marcelsud/kubectl
    commands:
      - echo $KUBECONFIG_DATA > /root/.kube/config
      - kubectl get pods --namespace=default --kubeconfig=/root/.kube/config
    secrets:
      - kubeconfig_data

#   publish-push:
#     image: plugins/docker
#     repo: marcelsud/demo
#     tags:
#       - ${DRONE_COMMIT_BRANCH}
#     force_tag: true
#     secrets: [ docker_username, docker_password ]
  
#       - kubectl set image deployment.apps/demo demo=marcelsud/demo:${DRONE_COMMIT_BRANCH} --namespace=default --kubeconfig=/root/.kube/config  
