pipeline:
  publish-push:
    image: plugins/docker
    repo: marcelsud/demo
    tags:
      - ${DRONE_COMMIT_BRANCH}
    force_tag: true
    secrets: [ docker_username, docker_password ]
  deploy:
    image: rancher/cli:v2.0.0
    commands:
      - kubectl config view --kubeconfig=/config/kubeconfig
    volumes:
      - /root/config/kubeconfig:/config/kubeconfig
