pipeline:
  debug:
    image: alpine:latest
    commands:
      - env
#     volumes:
#       - /config/kubeconfig:/config/kubeconfig
#   publish-push:
#     image: plugins/docker
#     repo: marcelsud/demo
#     tags:
#       - ${DRONE_COMMIT_BRANCH}
#     force_tag: true
#     secrets: [ docker_username, docker_password ]
  
#   deploy:
#     image: marcelsud/kubectl
#     commands:
#       - kubectl set image deployment.apps/demo demo=marcelsud/demo:${DRONE_COMMIT_BRANCH} --namespace=default --kubeconfig=/config/kubeconfig
#     volumes:
#       - /config/kubeconfig:/config/kubeconfig
