pipeline:
  setup:
    image: alpine:latest
    commands:
      - mkdir -p $HOME/.kube
      - echo $KUBECONFIG_DATA > /root/.kube/config
    secrets:
      - kubeconfig_data
    volumes:
      - /root/.kube/:/root/.kube/

  deploy:
    image: marcelsud/kubectl
    commands:
      - kubectl get pods --namespace=default --kubeconfig=/root/.kube/config
    volumes:
      - /root/.kube/:/root/.kube/

#   publish-push:
#     image: plugins/docker
#     repo: marcelsud/demo
#     tags:
#       - ${DRONE_COMMIT_BRANCH}
#     force_tag: true
#     secrets: [ docker_username, docker_password ]
  
#       - kubectl set image deployment.apps/demo demo=marcelsud/demo:${DRONE_COMMIT_BRANCH} --namespace=default --kubeconfig=/root/.kube/config  
