pipeline:
  setup:
    image: alpine:latest
    commands:
      - mkdir -p $HOME/.kube
      - echo $KUBECONFIG_DATA > /root/.kube/config
    secrets:
      - kubeconfig_data
    volumes:
      - /root/.kube/:/root/.kube/
  test:
    image: alpine:latest
    commands:
      - cat /root/.kube/config
    volumes:
      - /root/.kube/:/root/.kube/

#   publish-push:
#     image: plugins/docker
#     repo: marcelsud/demo
#     tags:
#       - ${DRONE_COMMIT_BRANCH}
#     force_tag: true
#     secrets: [ docker_username, docker_password ]
  
#   deploy:
#     image: marcelsud/kubectl
#     commands:
#       - kubectl set image deployment.apps/demo demo=marcelsud/demo:${DRONE_COMMIT_BRANCH} --namespace=default --kubeconfig=/config/kubeconfig
#     volumes:
#       - /config/kubeconfig:/config/kubeconfig
